#!/usr/bin/env python3
"""Build the theme-toggled icon set in ``icons/`` from ``tools/glyphs.json``.

Every icon is emitted twice:

* ``icons/light/<name>.svg`` -- tuned for GitHub's light theme (white canvas)
* ``icons/dark/<name>.svg``  -- tuned for GitHub's dark theme (#0d1117 canvas)

Both variants share the same geometry (48x48 grid, 13px corner radius) and the
same optical glyph size, so a ``<picture>`` swap is the only thing that changes
between themes -- no layout shift, no re-alignment.

Glyphs are auto-centred from their bounding box and scaled to a per-icon
optical target, which keeps the set visually even even though the source marks
have wildly different footprints (a 24x14 logotype next to a 15x15 frame).

Usage:  python3 tools/build_icons.py
Deps:   standard library only.
"""

from __future__ import annotations

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "tools", "glyphs.json")
OUT = os.path.join(ROOT, "icons")

GRID = 48          # icon canvas (also the rendered size in the README)
RADIUS = 13        # rounded-square corner radius
CENTER = GRID / 2  # 24

# Theme recipes. `tint` paints the rounded-square plate, `ink` the glyph.
# Light plate = brand wash over a white page; dark plate = brand wash lifted
# with a touch of white so it stays visible on #0d1117.
THEMES = {
    "light": {"base": None, "tint": 0.08, "edge": 0.18, "lift": 0.0},
    "dark": {"base": "#ffffff", "tint": 0.17, "edge": 0.10, "lift": 0.05},
}

# NOTE: XML forbids "--" inside comments, so this must not contain a dash pair.
HEADER = "<!-- Generated by tools/build_icons.py. Edit tools/glyphs.json and re-run. -->"


def fit(bbox, target, cx=CENTER, cy=CENTER, by="max"):
    """Scale + translate that centres `bbox` at (cx, cy) at optical `target`.

    `by="max"` fits the longest side (square tile icons); `by="height"` fits
    the height (the Gmail envelope, which is sized against the type).
    """
    x0, y0, x1, y1 = bbox
    w, h = x1 - x0, y1 - y0
    scale = target / (max(w, h) if by == "max" else h)
    tx = cx - scale * (x0 + w / 2)
    ty = cy - scale * (y0 + h / 2)
    return scale, tx, ty


def num(value):
    """Trim float noise so the emitted SVG stays diff-friendly."""
    return f"{value:.4f}".rstrip("0").rstrip(".")


def tile(theme, brand):
    """Rounded-square plate for one theme."""
    recipe = THEMES[theme]
    parts = []
    if recipe["base"]:
        parts.append(
            f'  <rect width="{GRID}" height="{GRID}" rx="{RADIUS}" '
            f'fill="{recipe["base"]}" fill-opacity="{recipe["lift"]}"/>'
        )
    parts.append(
        f'  <rect width="{GRID}" height="{GRID}" rx="{RADIUS}" '
        f'fill="{brand}" fill-opacity="{recipe["tint"]}"/>'
    )
    edge = "#ffffff" if theme == "dark" else brand
    parts.append(
        f'  <rect x=".5" y=".5" width="{GRID - 1}" height="{GRID - 1}" rx="{RADIUS - .5}" '
        f'fill="none" stroke="{edge}" stroke-opacity="{recipe["edge"]}"/>'
    )
    return "\n".join(parts)


def build_icon(name, spec, theme):
    colors = spec["colors"]
    scale, tx, ty = fit(spec["bbox"], spec["target"])
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{GRID}" height="{GRID}" viewBox="0 0 {GRID} {GRID}" role="img" aria-label="{spec['title']}">
{HEADER}
  <title>{spec['title']}</title>
{tile(theme, colors['brand'])}
  <path fill="{colors[theme]}" transform="translate({num(tx)} {num(ty)}) scale({num(scale)})" d="{spec['path']}"/>
</svg>
"""


# Pill geometry. `width` leaves the same 16px of breathing room on the right of
# the wordmark as there is on the left of the envelope.
GMAIL_LAYOUT = {
    "width": 182,
    "height": 56,
    "pad": 16,
    "envelope_height": 22,
    "text_x": 54,
}

GMAIL_THEMES = {
    "light": {"plate": "#ffffff", "edge": "#dadce0", "ink": "#202124", "muted": "#5f6368", "envelope": "#ea4335"},
    "dark": {"plate": "#161b22", "edge": "#30363d", "ink": "#e8eaed", "muted": "#9aa0a6", "envelope": "#ea4335"},
}


def build_gmail(badge, theme):
    """Pill badge: Gmail envelope + KPAHIMNA wordmark + @gmail.com."""
    c = GMAIL_THEMES[theme]
    l = GMAIL_LAYOUT
    env = badge["envelope"]
    # Envelope is centred on the badge's midline, not on its own grid centre.
    scale, _, ty = fit(env["bbox"], l["envelope_height"], cy=l["height"] / 2, by="height")
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{l['width']}" height="{l['height']}" viewBox="0 0 {l['width']} {l['height']}" role="img" aria-label="Email KPAHIMNA at gmail.com">
{HEADER}
  <title>Email KPAHIMNA</title>
  <rect x=".75" y=".75" width="{l['width'] - 1.5}" height="{l['height'] - 1.5}" rx="{l['height'] / 2 - .75}" fill="{c['plate']}" stroke="{c['edge']}"/>
  <g transform="translate({l['pad']} {num(ty)}) scale({num(scale)})">
    <path fill="{c['envelope']}" d="{env['path']}"/>
  </g>
  <path fill="{c['ink']}" d="{badge['wordmark']}"/>
  <path fill="{c['muted']}" d="{badge['subtitle']}"/>
</svg>
"""


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    return os.path.relpath(path, ROOT)


def main():
    data = json.load(open(DATA, encoding="utf-8"))
    written = []

    for theme in ("light", "dark"):
        for name, spec in data["icons"].items():
            written.append(write(f"{OUT}/{theme}/{name}.svg", build_icon(name, spec, theme)))
        written.append(write(f"{OUT}/{theme}/gmail.svg", build_gmail(data["gmail_badge"], theme)))

    print(f"wrote {len(written)} files:")
    for path in sorted(written):
        print("  " + path)


if __name__ == "__main__":
    main()
